# Lab | Imbalanced data

We will be using the files_for_lab/customer_churn.csv dataset to build a churn predictor.
Instructions

   1. Load the dataset and explore the variables.
   2. We will try to predict variable Churn using a logistic regression on variables tenure, SeniorCitizen,MonthlyCharges.
   3. Extract the target variable.
   4. Extract the independent variables and scale them.
   5. Build the logistic regression model.
   6. Evaluate the model.
   7. Even a simple model will give us more than 70% accuracy. Why?
   8. Synthetic Minority Oversampling TEchnique (SMOTE) is an over sampling technique based on nearest neighbors that adds new points between existing points. Apply imblearn.over_sampling.SMOTE to the dataset. Build and evaluate the logistic regression model. Is it there any improvement?
   9. Tomek links are pairs of very close instances, but of opposite classes. Removing the instances of the majority class of each pair increases the space between the two classes, facilitating the classification process. Apply imblearn.under_sampling.TomekLinks to the dataset. Build and evaluate the logistic regression model. Is it there any improvement?


## Importing Dependencies & Loading the Data

In [1]:
import pandas as pd
import numpy as np

In [5]:
customer_data = pd.read_csv("customer_churn.csv")
customer_data

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85   
1                  No               Mailed check          56.95        1889.5   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
4                 Yes           Electronic check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              Yes               Mailed check          84.80        1990.5   
7039              Yes    Credit card (automatic)         103.20        7362.9   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40         306.6   
7042              Yes  Bank transfer (automatic)         105.65        6844.5   

     Churn  
0       No  
1       No  
2      Yes  
3       No  
4      Yes  
...    ...  
7038    No  
7039    No  
7040    No  
7041   Yes  
7042    No  

[7043 rows x 21 columns]

## Data Exploration

In [6]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [ ]:
# above: we see no nans in the dataset
# below: we're briefly exploring the relevant variables according to our instructions

In [7]:
customer_data.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [8]:
customer_data.SeniorCitizen.unique()

array([0, 1], dtype=int64)

In [9]:
customer_data.MonthlyCharges.unique()

array([29.85, 56.95, 53.85, ..., 63.1 , 44.2 , 78.7 ])

In [10]:
customer_data.tenure.unique()

array([ 1, 34,  2, 45,  8, 22, 10, 28, 62, 13, 16, 58, 49, 25, 69, 52, 71,
       21, 12, 30, 47, 72, 17, 27,  5, 46, 11, 70, 63, 43, 15, 60, 18, 66,
        9,  3, 31, 50, 64, 56,  7, 42, 35, 48, 29, 65, 38, 68, 32, 55, 37,
       36, 41,  6,  4, 33, 67, 23, 57, 61, 14, 20, 53, 40, 59, 24, 44, 19,
       54, 51, 26,  0, 39], dtype=int64)

In [11]:
customer_data.Churn.unique()

array(['No', 'Yes'], dtype=object)

## Variable Extraction

In [12]:
X = customer_data[['SeniorCitizen', 'MonthlyCharges', 'tenure']]
y = customer_data['Churn']

In [13]:
display(X.head(3))
display(y.head(3)) #sanity checks

SeniorCitizen  MonthlyCharges  tenure
0              0           29.85       1
1              0           56.95      34
2              0           53.85       2

0     No
1     No
2    Yes
Name: Churn, dtype: object

In [14]:
y.value_counts(normalize=True) #this means that we have an imbalanced target variable

No     0.73463
Yes    0.26537
Name: Churn, dtype: float64

## Train/Test Split

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [17]:
y_train.value_counts(normalize=True) #this indicates that our model

No     0.733582
Yes    0.266418
Name: Churn, dtype: float64

In [18]:
y_test.value_counts(normalize=True) #we don't mind the imbalance here

No     0.738822
Yes    0.261178
Name: Churn, dtype: float64

## Scaling

In [19]:
scaler = MinMaxScaler() #we chose MinMaxScaler cause it doesn't assume the normality of our data

In [20]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Models

### 1. Logistic Regression

In [24]:
model = LogisticRegression()
model.fit(X_train, y_train)
pred_train = model.predict(X_train)
pred_test = model.predict(X_test)
print(classification_report(y_test, pred_test))
print(classification_report(y_train, pred_train))

              precision    recall  f1-score   support

          No       0.82      0.90      0.86      1041
         Yes       0.62      0.46      0.53       368

    accuracy                           0.78      1409
   macro avg       0.72      0.68      0.69      1409
weighted avg       0.77      0.78      0.77      1409

              precision    recall  f1-score   support

          No       0.82      0.91      0.87      4133
         Yes       0.66      0.46      0.54      1501

    accuracy                           0.79      5634
   macro avg       0.74      0.69      0.70      5634
weighted avg       0.78      0.79      0.78      5634



**Comment:** Accuracy here is almost 80% although there's a clear imbalance between No (86%) and Yes (53%). I think that might be because the F1 score on the No is so high. That means that our model has learned the 'No's of Churn much better than it did for the 'Yes's.

### 2. SMOTE (oversampling)

In [3]:
from imblearn.over_sampling import SMOTE

In [38]:
sm = SMOTE(k_neighbors=3)

X_train_SMOTE, y_train_SMOTE = sm.fit_resample(X_train, y_train)

In [39]:
model = LogisticRegression()
model.fit(X_train_SMOTE, y_train_SMOTE)
pred_train_SMOTE = model.predict(X_train_SMOTE)
pred_test_SMOTE = model.predict(X_test)
print(classification_report(y_test, pred_test_SMOTE))
print(classification_report(y_train_SMOTE, pred_train_SMOTE))

              precision    recall  f1-score   support

          No       0.88      0.72      0.79      1041
         Yes       0.47      0.71      0.57       368

    accuracy                           0.72      1409
   macro avg       0.68      0.72      0.68      1409
weighted avg       0.77      0.72      0.73      1409

              precision    recall  f1-score   support

          No       0.74      0.73      0.74      4133
         Yes       0.73      0.74      0.74      4133

    accuracy                           0.74      8266
   macro avg       0.74      0.74      0.74      8266
weighted avg       0.74      0.74      0.74      8266



**Comment:** Accuracy here is slightly reduced compared to the basic logistic regression model. This, imo, is a fair trade off since  the 'Yes's and the 'No's are perfectly balanced now (74%). The predictive strength of our model is still very descent but now what the model has learned is much more balanced, which is very valuable. This is with k_neighbors = 3. Adjusting for a much great value (k_neighbors >= 1000) both accuracy and F1 scores go up but ust slight (about 0.2%).

### 3. TomeKLink (downsampling)

In [23]:
from imblearn.under_sampling import TomekLinks

In [22]:
tl = TomekLinks(sampling_strategy='all')
X_train_TL, y_train_TL = tl.fit_resample(X_train, y_train)

In [26]:
model = LogisticRegression()
model.fit(X_train_TL, y_train_TL)
pred_train_TL = model.predict(X_train_TL)
pred_test_TL = model.predict(X_test)
print(classification_report(y_test, pred_test_TL))
print(classification_report(y_train_TL, pred_train_TL))

              precision    recall  f1-score   support

          No       0.83      0.90      0.86      1041
         Yes       0.63      0.46      0.53       368

    accuracy                           0.79      1409
   macro avg       0.73      0.68      0.70      1409
weighted avg       0.77      0.79      0.78      1409

              precision    recall  f1-score   support

          No       0.87      0.93      0.90      3744
         Yes       0.70      0.52      0.60      1112

    accuracy                           0.84      4856
   macro avg       0.78      0.73      0.75      4856
weighted avg       0.83      0.84      0.83      4856



**Comment:** Finally, this downsampling technique has yet again increased our model's accuracy. The trade off here was the balance of 'Yes's and 'No's. However, checking out the F1 scores (No - 90%, Yes - 60%). We see that our model can very accurately predict the 'No's. I would say that this model performs better than the logistic regression model but is still outperformed by the SMOTE regression model.

In [ ]:
#PS. I worked on this Lab with Victor.